services:
  - type: web
    name: bestbuy-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 3000
