services:
  - type: web
    name: ponzibackend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FRONTEND_URL
        value: https://ponzifrontend.vercel.app/
      - key: ADMIN_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
